### ISSUE TITLE
获取App支付的参数不正确，应该都是小写的

### ISSUE THREAD

**Issue by lxy1151** [gaoming13/wechat-php-sdk#11]
App支付 - 获取App支付的参数 签名参数错误，应该全部是小写的，没有大写的和公账号支付参数不通。

**Comment by gaoming13** [comment]
能再描述的清楚些吗 理解能力有限：）

**Comment by lxy1151** [comment]
原文：

    /**
     * App支付 - 获取App支付的参数
     * 用于移动客户端调用移动端SDK调起微信支付
     * @param string $prepayId 预生成订单ID
     * @return array
     */
    public function getWxPayAppApiParameters($prepayId)
    {
        // 获取App支付的参数
        $input = [
            // 应用ID
            'appId' => $this->appId,
            // 商户号
            'partnerid' => $this->mchId,
            // 预支付交易会话ID
            'prepayid' => $prepayId,
            // 扩展字段
            'package' => 'Sign=WXPay',
            // 随机字符串
            'nonceStr' => SHA1::get_random_str(32),
            // 时间戳
            'timestamp' => (string)time(),
        ];
        // 签名
        $input['paySign'] = SHA1::getSign2($input, 'key='.$this->key);
        return $input;
    }
正确的写法如下文：
    /**
     * App支付 - 获取App支付的参数
     * 用于移动客户端调用移动端SDK调起微信支付
     * @param string $prepayId 预生成订单ID
     * @return array
     */
    public function getWxPayAppApiParameters($prepayId)
    {
        // 获取App支付的参数
        $input = [
            // 应用ID
            'appid' => $this->appId,
            // 商户号
            'partnerid' => $this->mchId,
            // 预支付交易会话ID
            'prepayid' => $prepayId,
            // 扩展字段
            'package' => 'Sign=WXPay',
            // 随机字符串
            'noncestr' => SHA1::get_random_str(32),
            // 时间戳
            'timestamp' => (string)time(),
        ];
        // 签名
        $input['paySign'] = SHA1::getSign2($input, 'key='.$this->key);
        return json_encode($input);
    }

**Comment by lxy1151** [comment]
大小写的问题，导致签名始终错误

**Comment by lxy1151** [comment]
这是官方的还是个人维护的？

**Comment by gaoming13** [comment]
个人维护的
这个 getWxPayAppApiParameters 返回的就是数组
json_encode 需要自己处理下
```php
// 判断预订单是否生成成功
if ($wxOrder['return_code'] == 'SUCCESS' && $wxOrder['result_code'] == 'SUCCESS') {
    // 成功处理，获取App支付的参数
    $apiParams = $api->getWxPayAppApiParameters($wxOrder['prepay_id']);

    // 返回给app客户端
	return json_encode($apiParams);
} else {
	// 失败处理...
}
```

**Comment by lxy1151** [comment]
请，是参与签名的数据的键大小写错误了，导致签名错误；APP端获取到的参数发起支付提示签名错误

**Comment by lxy1151** [comment]
appId 要改为appid，nonceStr要改为noncestr，否则生成的签名是错误的

**Comment by lxy1151** [comment]
与公众号的支付参数有差别，微信的坑

**Comment by lxy1151** [comment]
QQ邮箱打开居然无法回复,汗！

**Comment by gaoming13** [comment]
好的 谢谢啦
