### ISSUE TITLE
在处理被动回复消息中每次都在进行accessAuth()URL接入验证，是否有必要？

### ISSUE THREAD

**Issue by dc236621911** [gaoming13/wechat-php-sdk#12]
你好：
我在看代码时，在Wechat.class.php中每次处理消息都在进行微信服务器url接入验证，这点是否和微信服务器流程冲突，还有就是是否有必要每次都进行验证？
谢谢……

**Comment by gaoming13** [comment]
就是判断了下 有无 `$_GET['echostr']`, 没有话是不验证的
