### ISSUE TITLE
微信授权时，获取到用户数据后下一步操作就报错

### ISSUE THREAD

**Issue by liuhaiqiang999** [gaoming13/wechat-php-sdk#18]
list($err, $user_info) =  (new Wechat())->api->get_userinfo_by_authorize('snsapi_userinfo');

        //处理异常
        if ($user_info == null) {
            var_dump($err);
        }else{
            var_dump($user_info);
            exit();
            Session::set($user_info);

        }
当var_dump数据的时候 完全正常 数据也都出来，但是写入数据库 或者写入session时等一系列操作就会报错  40163错误！！！！！

**Comment by gaoming13** [comment]
跟sdk应该没关系
