### ISSUE TITLE
Can you support php 5.5+

### ISSUE THREAD

**Issue by wanglongxiao** [gaoming13/wechat-php-sdk#2]
In your httpCurl class, post function.
[ErrorException]  
  curl_setopt(): The usage of the @filename API for file uploading is deprecated. Please use the CURLFile class instead

I am trying the dev_master branch.
thanks!

**Comment by wanglongxiao** [comment]
```
    ///*
    //update by Alex for php 5.5+
    //var_dump ($fields);
    curl_setopt($cl, CURLOPT_SAFE_UPLOAD, FALSE);
    if ( isset($fields['media']) ) {
        $tmpFile = str_replace("@","",$fields['media']);
        $fields = array('media' => new \CURLFile($tmpFile));
    }
    //*/
```

**Comment by gaoming13** [comment]
Thanks, I have fixed it in https://github.com/gaoming13/wechat-php-sdk/commit/368ea5b927742c1d52a030c3a742c8663c6550f4
