### ISSUE TITLE
貌似autoloader要求文件名不能含有.class

### ISSUE THREAD

**Issue by kkqy** [gaoming13/wechat-php-sdk#24]
目前用的thinkphp6，默认情况下用composer安装以后SDK主要的那两个类是放在xxx.class.php里面的，反而导致找不到这个类。
去掉文件名里的.class就正常了

**Comment by kkqy** [comment]
希望改进，以适应规范

**Comment by gaoming13** [comment]
v1.10.1 版本已修复
