### ISSUE TITLE
你好，这个SDK用来测试号可以吗？

### ISSUE THREAD

**Issue by jihuago** [gaoming13/wechat-php-sdk#3]
我用你这个框架用于测试号。总是接入不成功。

**Comment by gaoming13** [comment]
最早用测试号开发，测试号限制太多，可以自己申请个个人订阅号测试下

**Comment by gyf19** [comment]
@gaoming13  wechat-php-sdk 缺少 autoload.php 文件

**Comment by mengxiangbing** [comment]
是啊，缺少autoload.php 文件。autoload.php中的代码是干什么用的。也是封装成的函数吗？ @gaoming13

**Comment by gaoming13** [comment]
我瞅瞅看

**Comment by gaoming13** [comment]
autoload.php 文件已添加，autoload.php 是做自动加载该类库的命名空间

可以参见：[`http://php.net/manual/zh/function.autoload.php`](http://php.net/manual/zh/function.autoload.php)

一直用composer做自动加载，没有用到autoload.php，类库本身的autoload.php在一个版本就被去掉了

**Comment by mengxiangbing** [comment]
谢了。PHPer。这几天正好在写一些东西。
