### ISSUE TITLE
缺少发送模板消息接口

### ISSUE THREAD

**Issue by gyf19** [gaoming13/wechat-php-sdk#4]
缺少发送模板消息接口

**Comment by gyf19** [comment]
@gaoming13  楼主看看

**Comment by gaoming13** [comment]
我看看

**Comment by gaoming13** [comment]
@gyf19 :smile:  最近有点懒，中秋节补上

**Comment by gyf19** [comment]
@gaoming13  看来楼主说是18年中秋节 smile

**Comment by wangyandong** [comment]
楼主，今年的中秋节也过了，要不凑十一把模板消息给补上。
另外提个bug，获取素材的那个判断方式是错的，那个接口不返回errorcode，直接返回结果
